# Generated by Django 3.1.1 on 2020-09-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('picture_id', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('camera', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('cropped_picture', models.URLField(blank=True, null=True)),
                ('full_picture', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
            },
        ),
    ]
