# Generated by Django 3.1.1 on 2020-09-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='picture_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
